### ISSUE TITLE
Documento de Arquitectura

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/documento-de-arquitectura-trabajo-is#2]
[Practica 5 Documento arquitectura.pdf](https://github.com/SistemasTecTlaxiaco/documento-de-arquitectura-trabajo-is/files/6337744/Practica.5.Documento.arquitectura.pdf)

**Comment by Gerardo-79** [comment]
Calificación; 20/20

Cumple con todas las características solicitadas por el docente

**Comment by josealfredo79** [comment]
En el diagrama de clases se deben utilizar métodos
